### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by michaepr** [tkeskita/unstructured_grids#2]
Hello,

I've just installed your addon, which looks great (just like your other addons). I'm running Arch Linux with the Blender installation from the official repo. It looks like Inside Blender my local Python version 3.9.0 is running. When I press 'Extrude Cells' I get the error message

`Error: Python: Traceback (most recent call last):
  File "/home/.../.config/blender/2.91/scripts/addons/unstructured_grids-master/ug_extrude.py", line 110, in execute
    t0 = time.clock()
AttributeError: module 'time' has no attribute 'clock'`

I believe `time.clock()` is not supported in Python versions >=3.8. Would it be possible to update the script?

Thanks and all the best,
Michael

**Comment by tkeskita** [comment]
Hi, which version of Blender you are using? I thought they wouldn't be going beyond Python 3.7 yet because of compliance with vfxplatform.com, sounds strange. Blender is using it's own Python installation, so it shouldn't be running your local Python..?

**Comment by michaepr** [comment]
Hey, according to the PKGBUILD file (https://github.com/archlinux/svntogit-community/blob/packages/blender/trunk/PKGBUILD) the python that comes with blender is turned off and it's installed with python 3.9 instead.

**Comment by tkeskita** [comment]
Wow, that's adventurous of them. Good to know. OK, I'll add this to my TODO list, this seems like a small thing to fix, although it's a bit early to start going for Python 3.9.

**Comment by michaepr** [comment]
Ok that's great, thanks!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tkeskita** [comment]
Should be fixed now.
