### ISSUE TITLE
Can't find where "Print Face Info" outputs its data

### ISSUE THREAD

**Issue by emmett-b** [tkeskita/unstructured_grids#7]
Hi,

Sorry if it's not the right place for this. Feel free to delete it.
I'm glad this add-on exists, thank you for that.
Anyway, when I "Print Face Info", it says "1 face infos printed. See 'UG' Text Block." in the Blender "Info" window.
How do I get to this 'UG' text block?

**Comment by tkeskita** [comment]
Hi, you can see text blocks in the Blender Text Editor
https://docs.blender.org/manual/en/latest/editors/text_editor.html

**Comment by emmett-b** [comment]
Ah, yes, I looked at it but I didn't knew about the data-block menu:
![image](https://github.com/user-attachments/assets/89a46d60-c101-409e-b3ba-8c07cb2fe126)

Thanks!
